export const galleryImages = [  
    {
        id:1,
        title:"Audrey Parker",
        desc:"cartoon of a woman next to a bike",
        thumbSrc:"images/bikeaudrey-thumb.png",
        smSrc:"images/bikeaudrey-sm.png",
        fullSrc:"images/bikeaudrey.png",
        tags:["modern", "individual", "human", "all"]
    },
    {
        id:2,
        title:"Sydney",
        desc:"robot on a basic background",
        thumbSrc:"images/dreamsyd-thumb.png",
        smSrc:"images/dreamsyd-sm.png",
        fullSrc:"images/dreamsyd.png",
        tags:["scifi", "individual", "anthro", "all"],
    },
    {
        id:3,
        title:"Lady Cynthia",
        desc:"anthropomorphic wolf girl in fantasy winter clothing",
        thumbSrc:"images/cynthiaart-thumb.png",
        smSrc:"images/cynthiaart-sm.png",
        fullSrc:"images/cynthiaart.png",
        tags:["fantasy", "individual", "anthro", "all"]
    },
    {
        id:4,
        title:"The Golden Weaver",
        desc:"Spider-Man inspired superheroine in a dynamic pose",
        thumbSrc:"images/goldenweaver-thumb.png",
        smSrc:"images/goldenweaver-sm.png",
        fullSrc:"images/goldenweaver.png",
        tags:["modern", "individual", "human", "all"],
    },
    {
        id:5,
        title:"Big Stretch!",
        desc:"dragoness stretching in a room next to a bed",
        thumbSrc:"images/morninstretch-thumb.png",
        smSrc:"images/morninstretch-sm.png",
        fullSrc:"images/morninstretch.png",
        tags:["modern", "individual","anthro","background", "all"],
    },
    {
        id:6,
        title:"The Bounty Hunter",
        desc:"anthropomorphic wolf in Star-Wars inspired armor",
        thumbSrc:"images/starwarscyn-thumb.png",
        smSrc:"images/starwarscyn-sm.png",
        fullSrc:"images/starwarscyn.png",
        tags:["scifi", "individual", "anthro", "all"],
    },
    {
        id:7,
        title:"Goldweb",
        desc:"Spider-Man inspired character swinging on a web on a paint-spattered background",
        thumbSrc:"images/goldweb-thumb.png",
        smSrc:"images/goldweb-sm.png",
        fullSrc:"images/goldweb.png",
        tags:["modern", "individual", "human"],
    },
    {
        id:8,
        title:"Campfire Nights",
        desc:"A group of anthropomorphized animals in a group around a campfire, roasting marshmallows and chatting",
        thumbSrc:"images/campfire-thumb.png",
        smSrc:"images/campfire-sm.png",
        fullSrc:"images/campfire.png",
        tags:["modern", "group", "anthro", "background"],
    }];
    export const studioImages = [
    {
        id:1,
        title:"Sketches 1",
        desc:"collection of cartoons and sketches",
        thumbSrc:"images/studio1-thumb.png",
        smSrc:"images/studio1-sm.png",
        fullSrc:"images/studio1.png",
    },
    {
        id:2,
        title:"Sketches 2",
        desc:"collection of cartoons and sketches",
        thumbSrc:"images/studio2-thumb.png",
        smSrc:"images/studio2-sm.png",
        fullSrc:"images/studio2.png",
    },
    {
        id:3,
        title:"Sketches 3",
        desc:"very rough sketch of a knight with a sword",
        thumbSrc:"images/sketches-thumb.png",
        smSrc:"images/sketches-sm.png",
        fullSrc:"images/sketches.png",
    },
    {
        id:4,
        title:"Star Wars Sketch",
        desc:"very rough sketch of an anthropomorphic wolf in starwars inspired armor",
        thumbSrc:"images/sketches2-thumb.png",
        smSrc:"images/sketches2-sm.png",
        fullSrc:"images/sketches2.png",
    },
    {
        id:5,
        title:"Guardian Doodles",
        desc:"Rough traditional sketches of a robot in armor",
        thumbSrc:"images/guardiandoodles-thumb.png",
        smSrc:"images/guardiandoodles-sm.png",
        fullSrc:"images/guardiandoodles.png",
    }];
// {
//     id:,
//     title:,
//     desc:,
//     thumbSrc:"images/-thumb.png",
//     smSrc:"images/-sm.png",
//     fullSrc:"images/.png",
//     tags:[],
// },